times=('Palmeiras','Internacional','Fluminence','Corinthians','Flamengo','Athletico Paranaense','Atlético Mineiro','Fortaleza','São Paulo','América Mineiro','Botafogo','Santos','Goiás','Red Bull Bragantino','Coritiba','Cuiabá','Ceará','Atlético Goianiense','Avaí','Juventude')
print('=-'*30,'Times Do Brasileirão série A 2022','=-'*30)
print(times)
print('=-'*30,'Lista dos 5 primeiros colocados','=-'*30)
print(times[:5])
print('=-'*30,'Lista dos 4 últimos colocados','=-'*30)
print(times[16:])
print('=-'*30,'Lista dos times em ordem alfabética','=-'*30)
print(sorted(times))
print('=-'*30,f'o América Mineiro ficou na {times.index("Atlético Mineiro")+1}ª posição!','=-'*30)